---
- name: Установка и настройка Prometheus
  hosts: prometheus
  become: yes

  tasks:
    - name: Установка необходимых пакетов
      apt:
        name: '{{ packages }}'
        state: latest
        update_cache: yes
      vars:
        packages:
          - wget
          - tar

    - name: Создание пользователя Prometheus
      user:
        name: prometheus
        shell: /bin/false
        system: yes
        create_home: true

    - name: Удаление существующего файла /opt/prometheus, если он существует
      file:
        path: /opt/prometheus
        state: absent
      failed_when: false
      changed_when: false

    - name: Убедиться, что директории Prometheus существуют
      file:
        path: '{{ item }}'
        state: directory
        owner: prometheus
        group: prometheus
        mode: '0755'
      loop:
        - /opt/prometheus
        - /opt/prometheus/consoles
        - /opt/prometheus/console_libraries
        - /opt/prometheus/data

    - name: Загрузка Prometheus
      get_url:
        url: 'https://github.com/prometheus/prometheus/releases/download/v2.37.0/prometheus-2.37.0.linux-amd64.tar.gz'
        dest: '/tmp/prometheus.tar.gz'
        mode: '0644'

    - name: Распаковка Prometheus
      unarchive:
        src: '/tmp/prometheus.tar.gz'
        dest: '/opt/prometheus'
        remote_src: yes
        extra_opts: ['--strip-components=1']
        creates: '/opt/prometheus/prometheus'

    - name: Настройка службы systemd для Prometheus
      template:
        src: prometheus.service.j2
        dest: /etc/systemd/system/prometheus.service
      notify: перезапустить prometheus

    - name: Запуск и включение службы Prometheus
      systemd:
        name: prometheus
        enabled: yes
        state: started

  handlers:
    - name: перезапустить prometheus
      systemd:
        name: prometheus
        state: restarted
