---
- name: Управление пользователями и их правами
  hosts: all
  become: yes
  vars:
    user_name: 'TestUser1'
    user_password: 'TestUser1'
  tasks:
    - name: Исправление прерванного процесса dpkg
      shell: dpkg --configure -a
      async: 45
      poll: 0
      register: dpkg_configure

    - name: Wait for dpkg --configure -a to complete
      async_status:
        jid: '{{ dpkg_configure.ansible_job_id }}'
      register: job_result
      until: job_result.finished
      retries: 30
      delay: 10

    - name: Создание нового пользователя
      user:
        name: '{{ user_name }}'
        password: '{{ user_password}}'
        shell: /bin/bash
        state: present

    - name: Добавление пользователя в sudoers
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^{{ user_name }}'
        line: '{{ user_name }} ALL=(ALL) NOPASSWD:ALL'
