---
- name: Установка и настройка веб-сервера Nginx
  hosts: all
  become: yes
  tasks:
    - name: Исправление прерванного процесса dpkg
      shell: dpkg --configure -a
      async: 45
      poll: 0
      register: dpkg_configure

    - name: Ожидание завершения dpkg --configure -a
      async_status:
        jid: '{{ dpkg_configure.ansible_job_id }}'
      register: job_result
      until: job_result.finished
      retries: 30
      delay: 10

    - name: Установка Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Обеспечение запуска Nginx при старте системы
      systemd:
        name: nginx
        enabled: yes

    - name: Запуск Nginx
      systemd:
        name: nginx
        state: started
