---
- name: Обновление системы
  hosts: all
  become: yes
  tasks:
    - name: Исправление прерванного процесса dpkg
      shell: dpkg --configure -a
      async: 45
      poll: 0
      register: dpkg_configure

    - name: Wait for dpkg --configure -a to complete
      async_status:
        jid: '{{ dpkg_configure.ansible_job_id }}'
      register: job_result
      until: job_result.finished
      retries: 30
      delay: 10

    - name: Обновление всех пакетов
      apt:
        update_cache: yes
        upgrade: dist

    - name: Перезагрузка сервера
      reboot:
        msg: 'Перезагрузка для завершения обновления'
        reboot_timeout: 600
